name: ${project.artifactId}
main: ${project.groupId}.Engine
version: ${project.version}
softdepend: [Vault]
loadbefore: [Essentials]
authors: [steffansk1997, Tofuus]
description: >
             RolePlay Engine
commands:
  card:
    description: Roleplay Character card
  RP:
    description: Switch to RolePlay Chat
  OOC:
    description: Switch to Out of Character Chat
  whisper:
    description: Whisper something
    aliases: w
  shout:
    description: Whisper something
    aliases: s
  rpengine:
    description: Admin Command of the RP engine
    permission: rpengine.admin
  bird:
    description: Send a bird
  countdown:
    description: Starts a countdown
  roll:
    description: Rolls from a number
  toggleooc:
    description: Toggle the ooc chat
  spawnpoint:
    description: Teleport command for nation spawnpoints
    aliases: [nationspawn, rpspawn, nationhome, rphome]
  rpconfig:
    description: Configure RPEngine

permissions:
  #Spawnpoint permissions
  rpengine.spawnpoint.set.own:
    description: Allows you to your own nations spawnpoint
  rpengine.spawnpoint.set.all:
    description: Allows you to set the spawnpoint for all nations
  rpengine.spawnpoint.own:
    description: Allows teleport to own nations spawnpoint
  rpengine.spawnpoint.others:
    description: Allows teleport to other nations

  #Chat perms
  rpengine.chat.color:
    description: Allows you to use colors in the chat

  #rpconfig perms
  rpengine.rpconfig:
    decription: allows you to open the rpconfig menu
  rpengine.rpconfig.races:
    decription: allows you to open the races menu
  rpengine.rpconfig.nations:
    decription: allows you to open the nation menu
  rpengine.rpconfig.rprange:
    decription: Allows you to edit the range of the RP chat
    children:
      rpengine.rpconfig: true
  rpengine.rpconfig.whisperrange:
    decription: Allows you to edit the range of whisper messages
    children:
      rpengine.rpconfig: true
  rpengine.rpconfig.shoutrange:
    decription: Allows you to edit the range of shout messages
    children:
      rpengine.rpconfig: true
  rpengine.rpconfig.maxage:
    decription: Allows you to edit the global max age
    children:
      rpengine.rpconfig: true
  rpengine.rpconfig.birdspeed:
    decription: Allows you to edit the global max age
    children:
      rpengine.rpconfig: true
  rpengine.rpconfig.maxroll:
    decription: Allows you to edit the global max age
    children:
      rpengine.rpconfig: true
  rpengine.rpconfig.maxcountdown:
    decription: Allows you to edit the global max age
    children:
      rpengine.rpconfig: true
  rpengine.rpconfig.cooldown:
    decription: Allows you to edit the global max age
    children:
      rpengine.rpconfig: true
  rpengine.rpconfig.create.nations:
    decription: Allows you to create new nations
    children:
      rpengine.rpconfig: true
      rpengine.rpconfig.nations: true
  rpengine.rpconfig.create.races:
    decription: Allows you to create new races
    children:
      rpengine.rpconfig: true
      rpengine.rpconfig.races: true
  rpengine.rpconfig.delete.nations:
    decription: Allows you to delete nations
    children:
      rpengine.rpconfig: true
      rpengine.rpconfig.nations: true
  rpengine.rpconfig.delete.races:
    decription: Allows you to delete races
    children:
      rpengine.rpconfig: true
      rpengine.rpconfig.races: true
  rpengine.rpconfig.edit.nations:
    decription: Allows you to edit nations
    children:
      rpengine.spawnpoint.set.all: true
      rpengine.rpconfig: true
      rpengine.rpconfig.nations: true
  rpengine.rpconfig.edit.races:
    decription: Allows you to edit nations
    children:
      rpengine.rpconfig: true
      rpengine.rpconfig.races: true
  rpengine.rpconfig.*:
    decription: Wildcard to all rpconfig commands
    children:
      rpengine.rpconfig: true
      rpengine.rpconfig.races: true
      rpengine.rpconfig.nations: true
      rpengine.rpconfig.create.nations: true
      rpengine.rpconfig.delete.nations: true
      rpengine.rpconfig.edit.nations: true
      rpengine.rpconfig.create.races: true
      rpengine.rpconfig.delete.races: true
      rpengine.rpconfig.edit.races: true
      rpengine.rpconfig.rprange: true
      rpengine.rpconfig.whisperrange: true
      rpengine.rpconfig.shoutrange: true
      rpengine.rpconfig.maxage: true
      rpengine.rpconfig.birdspeed: true
      rpengine.rpconfig.maxroll: true
      rpengine.rpconfig.maxcountdown: true
      rpengine.rpconfig.cooldown: true
